#!/usr/bin/env python3
"""
BOT RUNNER — connects to the arena and hot-reloads your brain.

DO NOT EDIT THIS FILE. Edit brain.py for your strategy, loadout.py for your gear.

When you save brain.py, your strategy reloads LIVE — no disconnect, no restart.
Your bot keeps its score, HP, and position while you iterate.

Usage:
    python bot.py --name "YourBotName" --server http://SERVER_IP:33333
"""

import os
import sys
import time
import argparse
import traceback
import requests
from pathlib import Path

BOT_DIR = Path(__file__).parent


# ---------------------------------------------------------------------------
# Server communication
# ---------------------------------------------------------------------------

class ArenaClient:
    def __init__(self, server_url):
        self.server = server_url.rstrip("/")
        self.token = None
        self.player_id = None

    def join(self, name, gear=None):
        try:
            payload = {"name": name}
            if gear:
                payload["loadout"] = gear
            resp = requests.post(
                self.server + "/game/join", json=payload, timeout=5)
        except requests.ConnectionError:
            print("\n  Could not connect to " + self.server)
            print("  Is the game server running? Check the IP on the big screen.\n")
            sys.exit(1)

        data = resp.json()
        if "error" in data:
            print("\n  " + data["error"] + "\n")
            sys.exit(1)

        self.token = data["token"]
        self.player_id = data["player-id"]
        return data

    def get_state(self):
        try:
            resp = requests.get(
                self.server + "/game/state",
                headers={"Authorization": self.token},
                timeout=3)
            return resp.json()
        except Exception:
            return None

    def send_action(self, action, direction=None):
        body = {"action": action}
        if direction:
            body["direction"] = direction
        try:
            requests.post(
                self.server + "/game/action",
                headers={"Authorization": self.token},
                json=body, timeout=3)
        except Exception:
            pass

    def select_gear(self, item_key):
        try:
            resp = requests.post(
                self.server + "/game/gear/select",
                headers={"Authorization": self.token},
                json={"item": item_key},
                timeout=5)
            return resp.json()
        except Exception:
            return None

    def get_status(self):
        try:
            return requests.get(
                self.server + "/game/status", timeout=3).json()
        except Exception:
            return None


# ---------------------------------------------------------------------------
# Hot-reload brain — watches brain.py for changes, reloads on save
# ---------------------------------------------------------------------------

class HotBrain:
    def __init__(self, bot_dir, on_reload=None):
        self.bot_dir = Path(bot_dir)
        self.brain_path = self.bot_dir / "brain.py"
        self._think_fn = None
        self._last_mtimes = {}
        self._load_count = 0
        self._on_reload = on_reload
        self._reload()

    def _get_mtimes(self):
        mtimes = {}
        for f in self.bot_dir.glob("*.py"):
            if f.name == "bot.py":
                continue
            try:
                mtimes[str(f)] = os.path.getmtime(f)
            except OSError:
                pass
        return mtimes

    def _reload(self):
        if not self.brain_path.exists():
            print("  [hot-reload] brain.py not found!")
            return

        namespace = {}
        try:
            code = self.brain_path.read_text()
            compiled = compile(code, str(self.brain_path), "exec")
            exec(compiled, namespace)  # noqa: S102 — intentional for hot-reload
        except Exception:
            print("  [hot-reload] SYNTAX ERROR in brain.py:")
            traceback.print_exc()
            print("  [hot-reload] Keeping previous brain. Fix and save again.")
            return

        if "think" not in namespace:
            print("  [hot-reload] brain.py needs a think() function!")
            return

        self._think_fn = namespace["think"]
        self._load_count += 1
        self._last_mtimes = self._get_mtimes()

        if self._load_count == 1:
            print("  [brain] Loaded brain.py")
        else:
            print("  [brain] RELOADED brain.py (v" + str(self._load_count) + ") -- new strategy is LIVE!")
            if self._on_reload:
                self._on_reload(self._load_count)

    def check_reload(self):
        current = self._get_mtimes()
        if current != self._last_mtimes:
            self._reload()

    def think(self, state):
        if self._think_fn is None:
            return None, None
        try:
            result = self._think_fn(state)
            if result is None:
                return None, None
            return result
        except Exception:
            print("  [brain] ERROR in think():")
            traceback.print_exc()
            return None, None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Bot Battle Arena")
    parser.add_argument("--name", default=None, help="Your bot's arena name")
    parser.add_argument("--server", default="http://localhost:33333",
                        help="Game server URL")
    args = parser.parse_args()

    # Load loadout
    loadout = {"name": "MyBot", "gear": []}
    loadout_path = BOT_DIR / "loadout.py"
    if loadout_path.exists():
        ns = {}
        compiled = compile(loadout_path.read_text(), str(loadout_path), "exec")
        exec(compiled, ns)  # noqa: S102
        if "LOADOUT" in ns:
            loadout = ns["LOADOUT"]

    if args.name:
        loadout["name"] = args.name

    bot_name = loadout.get("name", "MyBot")
    gear_list = loadout.get("gear", [])

    print()
    print("  +======================================+")
    print("  |  " + bot_name.center(34) + "  |")
    print("  +======================================+")
    print("  |  Server: " + args.server.ljust(27) + "|")
    print("  |  Gear:   " + str(gear_list)[:27].ljust(27) + "|")
    print("  |                                      |")
    print("  |  Edit brain.py -- auto-reloads live! |")
    print("  +======================================+")
    print()

    # Connect
    client = ArenaClient(args.server)
    client.join(bot_name)
    print("  Joined as " + bot_name + " (" + client.player_id + ")")

    # Select gear
    for item in gear_list:
        result = client.select_gear(item)
        if result and "error" in result:
            print("  Gear '" + item + "': " + result["error"])
            avail = [k for k, v in result.get("gear-catalog", {}).items()
                     if v.get("available")]
            if avail:
                print("  Still available: " + ", ".join(avail))
        elif result:
            print("  Equipped: " + item)

    # Wait for game to start — poll /game/status (no auth needed)
    print("\n  Waiting in lobby... (watch the big screen!)")
    while True:
        status = client.get_status()
        if status and status.get("phase") not in ("lobby", "armory"):
            break
        time.sleep(0.5)
    print("  GAME ON! Let's go!\n")

    # Init hot-reload brain with server notification
    def on_brain_reload(version):
        try:
            requests.post(
                client.server + "/game/bot-update",
                headers={"Authorization": client.token},
                json={}, timeout=3)
        except Exception:
            pass

    brain = HotBrain(BOT_DIR, on_reload=on_brain_reload)

    tick_count = 0
    last_score = 0

    while True:
        try:
            # Check for brain.py changes every ~1 second
            if tick_count % 4 == 0:
                brain.check_reload()

            state = client.get_state()
            if state is None:
                print("  Connection lost -- retrying...")
                time.sleep(2)
                continue

            # Check phase via status endpoint (no auth needed, always works)
            status = client.get_status()
            if status and status.get("phase") in ("lobby", "armory"):
                time.sleep(1)
                continue

            me = state.get("you", {})
            if not me.get("alive?", True):
                time.sleep(0.25)
                continue

            action, direction = brain.think(state)
            if action:
                client.send_action(action, direction)

            tick_count += 1
            score = me.get("score", 0)

            if tick_count % 20 == 0:
                alive = "ALIVE" if me.get("alive?", False) else "DEAD"
                enemies = len(state.get("visible", {}).get("enemies", []))
                players = len(state.get("visible", {}).get("players", []))
                print("  tick %5s | %s | HP %4s | Score %5d | "
                      "Ammo %2s | Enemies %d | Rivals %d"
                      % (state.get("tick", "?"), alive,
                         me.get("hp", "?"), score,
                         me.get("ammo", "?"), enemies, players))

            if score > last_score:
                print("  >>> +%d points! (total: %d)" % (score - last_score, score))
                last_score = score

            time.sleep(0.25)

        except KeyboardInterrupt:
            print("\n  " + bot_name + " stopped. GG!")
            break
        except requests.exceptions.ConnectionError:
            print("  Connection lost -- retrying in 2s...")
            time.sleep(2)
        except Exception as e:
            print("  Error: " + str(e))
            time.sleep(1)


if __name__ == "__main__":
    main()
